# Generated by Django 4.1.7 on 2023-04-08 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='Products')),
                ('name', models.CharField(max_length=264)),
                ('preview_text', models.TextField(blank=True, max_length=200, null=True, verbose_name='Preview Text')),
                ('detail_text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(default=0.0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='App_Shop.category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Shop.category')),
            ],
            options={
                'verbose_name_plural': 'Sub-Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_image_one', models.ImageField(upload_to='Products')),
                ('side_image_two', models.ImageField(upload_to='Products')),
                ('network', models.TextField(blank=True, max_length=255, null=True)),
                ('os', models.TextField(blank=True, max_length=255, null=True)),
                ('memory', models.TextField(blank=True, max_length=255, null=True)),
                ('camera', models.TextField(blank=True, max_length=255, null=True)),
                ('battery', models.TextField(blank=True, max_length=255, null=True)),
                ('display', models.TextField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='App_Shop.product')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Shop.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Details',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='App_Shop.subcategory'),
        ),
    ]
