# Generated by Django 4.1.7 on 2023-04-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
