# Generated by Django 4.1.7 on 2023-04-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0002_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
